### ISSUE TITLE
Compilation error on Windows

### ISSUE THREAD

**Issue by MarcroSoft** [svpv/ppmd-mini#3]
I can't compile this with mingw-w64 on windows.
This is one of the errors I get:
ppmd-mini.c: In function 'main':                                                                                        
ppmd-mini.c:205:8: error: lvalue required as left operand of assignment                                                 
  205 |  stdin = freopen(fname, "r", stdin);                                                                             
I think it's because mingw uses stdin and stdout differently than unix.
It compiles on cygwin though.
Is there a way to get it working with the native mingw gcc for windows?
Thanks,
Marc

**Comment by zamazan4ik** [comment]
@MarcroSoft unfortunately - no. The original author has died: https://www.altlinux.org/Team/Famous#Alexey_Tourbin (if you understand Russian).

So this library is unmaintained.
